### ISSUE TITLE
Documentation: word missing in output

### ISSUE THREAD

**Issue by spadgos** [eslint/eslint.github.io#61]
*(Copied from eslint/eslint#2297)*

On [Working with rules](http://eslint.org/docs/developer-guide/working-with-rules) under the `context.report()` heading, the source reads:

    context.report(node, "`{{identifier}}` is unexpected!", { identifier: node.name });

But the output shows:

![selection_006](https://cloud.githubusercontent.com/assets/426222/7111744/77ed9aa4-e206-11e4-9504-35df11cfce4c.png)

**Comment by spadgos** [comment]
Fixed in https://github.com/eslint/eslint/pull/2299

**Comment by bgw** [comment]
I think this should be reopened. The fix didn't really work (eslint/eslint#2299 followed by eslint/eslint#2502), and it's still broken on the website.
